version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: tgb-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gfWUIR
    volumes:
      - ./tgb/mongodb/data:/data

  tgb:
    image: tgb
    build:
      dockerfile: ./Dockerfile
    container_name: tgb-tgb
    restart: always
    volumes:
      - ./tgb/answer:/app/answers



